# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 634362948c1f0523f0ec8f5c2dbcd889a18ffa16a0aa5d90c7c86d1c077690e1bfe3dfab1d3f00e0c9e892ceb43f20ed46cc0d89b6dde0d94b3c56d3501e5414

test:
  secret_key_base: faa4bedc8f79c89e1526faeeda6b8d72c5c58c560858b66f760ac725cbbbf2cdfe0d989f4b5ddd7680586179d422f8d559d174a8d39b9c6194f35950bd8f7aff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
