AllCops:
  Exclude:
    - bin/*
    - db/migrate/*
    - db/schema.rb
    - db/seeds.rb
    - db/seeds/*

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false