version: "3"
services:
  db:
    image: postgres
    env_file:
      - ./config/db.env
    networks:
      - backend
    volumes:
      - ./db:/var/lib/postgresql/data

  proxy:
    build: ./proxy
    restart: always
    depends_on:
      - api
      - web
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy

  api:
    build:
      context: ./api
      args:
        RUBY_VERSION: "3.0.0"
        EXECJS_RUNTIME: Node
    depends_on:
      - db
    env_file:
      - ./config/api.env
    networks:
      - proxy
      - backend
    volumes:
      - ./api:/srv/www-api

  web:
    build:
      context: ./web
    stdin_open: true
    env_file:
      - ./config/web.env
    environment:
      - API_URL=http://localhost/backend/graphql
      - "WEB_PORT=${LONGBOX_WEB_PORT}"

    networks:
      - proxy
      - frontend
    volumes:
      - ./web:/srv/www
      - "/srv/www/node_modules"

networks:
  proxy:
  backend:
  frontend:

volumes:
  db:
