version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    networks:
      - backend
    volumes:
      - ./db:/var/lib/postgresql/data

  api:
    build: ./api
    depends_on:
      - db
    environment:
      RAILS_ENV: "${RAILS_ENV}"
      DATABASE_URL: postgres://postgres:@db
      DATABASE_USER: "${POSTGRES_USER}"
      DATABASE_PASSWORD: "${POSTGRES_PASSWORD}"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    networks:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./api:/srv/www-api

networks:
  backend:

volumes:
  db:
