services:
  db:
    volumes:
      - ./db/local:/var/lib/postgresql/data
    ports:
      - ${LONGBOX_DB_PORT:-5432}:5432

  proxy:
    build: ./proxy
    ports:
      - ${LONGBOX_PROXY_PORT:-80}:80
      - ${LONGBOX_PROXY_PORT_SSL:-443}:443

  api:
    build:
      context: ./api
      args:
        RUBY_VERSION: "3.0.0"
        RAILS_ENV: development
        NODE_ENV: development
    ports:
      - "${LONGBOX_API_PORT:-3000}:3000"
    volumes:
      - ./api:/build

  web:
    build:
      context: ./web
      target: build
    command: yarn start:dev
    ports:
      - "${LONGBOX_WEB_PORT:-3001}:3000"
    volumes:
      - ./web:/srv/www
      - /srv/www/node_modules

volumes:
  api:
  web:
  db:
