version: "3"
services:
  db:
    image: postgres
    env_file: .env-db
    networks:
      - backend
    volumes:
      - ./db:/var/lib/postgresql/data

  proxy:
    build: ./proxy
    restart: always
    depends_on:
      - api
      - web
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy

  api:
    build:
      context: ./api
      args:
        RUBY_VERSION: "3.0.0"
        EXECJS_RUNTIME: Node
        RAILS_ENV: development
        NODE_ENV: development
    depends_on:
      - db
    env_file: .env-api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    networks:
      - proxy
      - backend
    volumes:
      - ./api:/srv/www-api

  web:
    build:
      context: ./web
    stdin_open: true
    env_file: .env-web
    networks:
      - proxy
      - frontend
    volumes:
      - ./web:/srv/www
      - "/srv/www/node_modules"

networks:
  proxy:
  backend:
  frontend:

volumes:
  db:
