version: "3"

services:
  db:
    image: postgres
    env_file:
      - ./config/db.env
    networks:
      - backend

  proxy:
    restart: always
    depends_on:
      - api
      - web
    networks:
      - proxy

  api:
    depends_on:
      - db
    env_file:
      - ./config/api.env
    networks:
      - proxy
      - backend
    build:
      args:
        RUBY_VERSION: "3.0.2"

  web:
    stdin_open: true
    env_file:
      - ./config/web.env
    environment:
      - API_URL=http://api/backend/graphql
    networks:
      - proxy
      - frontend

networks:
  proxy:
  backend:
  frontend:
