version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
    - ./db:/var/lib/postgresql/data
  web:
    build: ./api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/srv
    ports:
      - "3000:3000"
    environment:
      PG_PASSWORD: password
    depends_on:
      - db

volumes:
  db: