version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USERNAME: "${DATABASE_USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    networks:
      - backend
    volumes:
      - ./db:/var/lib/postgresql/data

  api:
    build: ./api
    depends_on:
      - db
    environment:
      RAILS_ENV: "${RAILS_ENV}"
      DATABASE_URL: "${DATABASE_URL}"
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_USERNAME: "${DATABASE_USERNAME}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    networks:
      - backend
    ports:
      - "3001:3001"
    volumes:
      - ./api:/srv/www-api

  web:
    build: ./web
    stdin_open: true
    environment:
      API_URL: "${API_URL}"
    networks:
      - frontend
    volumes:
      - ./web:/srv/www
      - "/srv/www/node_modules"
    ports:
      - "3000:3000"

networks:
  backend:
  frontend:

volumes:
  db:
