import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
export type Maybe<T> = T | null;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
const defaultOptions =  {}
export const namedOperations = {
  Query: {
    Book: 'Book',
    Books: 'Books',
    Creator: 'Creator',
    Publisher: 'Publisher',
    Publishers: 'Publishers',
    RankedBookList: 'RankedBookList',
    RankedPublisherList: 'RankedPublisherList',
    RankedSeriesList: 'RankedSeriesList',
    Series: 'Series'
  },
  Mutation: {
    CreatePublisher: 'CreatePublisher',
    Login: 'Login',
    LogOut: 'LogOut',
    Register: 'Register',
    UpdatePublisher: 'UpdatePublisher',
    UpdateSeries: 'UpdateSeries'
  }
}
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  DateTime: any;
};

export type AuthenticationResult = {
  __typename?: 'AuthenticationResult';
  accessToken: Scalars['String'];
  me?: Maybe<User>;
  refreshToken: Scalars['String'];
};

/** A comic book or trade paperback */
export type Book = {
  __typename?: 'Book';
  ageRating?: Maybe<Scalars['String']>;
  alternateTitle?: Maybe<Scalars['String']>;
  createdAt: Scalars['DateTime'];
  credits?: Maybe<Array<Credit>>;
  displayName: Scalars['String'];
  format?: Maybe<Scalars['String']>;
  id: Scalars['ID'];
  issue?: Maybe<Scalars['String']>;
  pageCount?: Maybe<Scalars['String']>;
  price?: Maybe<Scalars['String']>;
  publicationDate?: Maybe<Scalars['String']>;
  publisher?: Maybe<Publisher>;
  publisherName?: Maybe<Scalars['String']>;
  series?: Maybe<Series>;
  seriesName?: Maybe<Scalars['String']>;
  summary?: Maybe<Scalars['String']>;
  updatedAt: Scalars['DateTime'];
};

/** The connection type for Book. */
export type BookConnection = {
  __typename?: 'BookConnection';
  /** A list of edges. */
  edges?: Maybe<Array<Maybe<BookEdge>>>;
  /** A list of nodes. */
  nodes?: Maybe<Array<Maybe<Book>>>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
};

/** An edge in a connection. */
export type BookEdge = {
  __typename?: 'BookEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['String'];
  /** The item at the end of the edge. */
  node?: Maybe<Book>;
};

export type BookInput = {
  ageRating?: Maybe<Scalars['String']>;
  alternateTitle?: Maybe<Scalars['String']>;
  creditIds?: Maybe<Array<Scalars['ID']>>;
  format?: Maybe<Scalars['String']>;
  issue?: Maybe<Scalars['String']>;
  pageCount?: Maybe<Scalars['String']>;
  price?: Maybe<Scalars['String']>;
  publicationDate?: Maybe<Scalars['String']>;
  seriesId?: Maybe<Scalars['ID']>;
  summary?: Maybe<Scalars['String']>;
};

/** Autogenerated return type of CreateBook */
export type CreateBookPayload = {
  __typename?: 'CreateBookPayload';
  book?: Maybe<Book>;
  errors: Array<UserError>;
};

/** Autogenerated return type of CreatePublisher */
export type CreatePublisherPayload = {
  __typename?: 'CreatePublisherPayload';
  /** In case of failure, there will be errors in this list */
  errors: Array<UserError>;
  publisher?: Maybe<Publisher>;
};

/** A person representing someone involved in the creation process of a book */
export type Creator = {
  __typename?: 'Creator';
  createdAt: Scalars['DateTime'];
  credits: Array<Credit>;
  firstName?: Maybe<Scalars['String']>;
  id: Scalars['ID'];
  lastName?: Maybe<Scalars['String']>;
  updatedAt: Scalars['DateTime'];
};

/** An association of book and creator */
export type Credit = {
  __typename?: 'Credit';
  book: Book;
  createdAt: Scalars['DateTime'];
  creator: Creator;
  id: Scalars['ID'];
  role: Scalars['String'];
  updatedAt: Scalars['DateTime'];
};


export type LogInInput = {
  email: Scalars['String'];
  password: Scalars['String'];
};

export type LogOutInput = {
  everywhere?: Maybe<Scalars['Boolean']>;
};

export type Message = {
  __typename?: 'Message';
  message: Scalars['String'];
};

export type Mutation = {
  __typename?: 'Mutation';
  createBook?: Maybe<CreateBookPayload>;
  createPublisher?: Maybe<CreatePublisherPayload>;
  createSeries?: Maybe<Series>;
  createUser?: Maybe<AuthenticationResult>;
  login?: Maybe<AuthenticationResult>;
  logout?: Maybe<Message>;
  refreshSession?: Maybe<AuthenticationResult>;
  register?: Maybe<AuthenticationResult>;
  updateBook?: Maybe<UpdateBookPayload>;
  updatePublisher?: Maybe<UpdatePublisherPayload>;
  updateSeries?: Maybe<UpdateSeriesPayload>;
};


export type MutationCreateBookArgs = {
  attributes: BookInput;
};


export type MutationCreatePublisherArgs = {
  attributes: PublisherInput;
};


export type MutationCreateSeriesArgs = {
  name: Scalars['String'];
  publisherId: Scalars['ID'];
};


export type MutationCreateUserArgs = {
  input: RegistrationInput;
};


export type MutationLoginArgs = {
  input: LogInInput;
};


export type MutationLogoutArgs = {
  input: LogOutInput;
};


export type MutationRegisterArgs = {
  input: RegistrationInput;
};


export type MutationUpdateBookArgs = {
  id: Scalars['ID'];
  attributes: BookInput;
};


export type MutationUpdatePublisherArgs = {
  id: Scalars['ID'];
  attributes: PublisherInput;
};


export type MutationUpdateSeriesArgs = {
  id: Scalars['ID'];
  attributes: SeriesInput;
};

/** Information about pagination in a connection. */
export type PageInfo = {
  __typename?: 'PageInfo';
  /** When paginating forwards, the cursor to continue. */
  endCursor?: Maybe<Scalars['String']>;
  /** When paginating forwards, are there more items? */
  hasNextPage: Scalars['Boolean'];
  /** When paginating backwards, are there more items? */
  hasPreviousPage: Scalars['Boolean'];
  /** When paginating backwards, the cursor to continue. */
  startCursor?: Maybe<Scalars['String']>;
};

/** A book publishing company */
export type Publisher = {
  __typename?: 'Publisher';
  bookCount: Scalars['Int'];
  createdAt: Scalars['DateTime'];
  id: Scalars['ID'];
  name: Scalars['String'];
  series: Array<Series>;
  seriesCount: Scalars['Int'];
  updatedAt: Scalars['DateTime'];
};

/** The connection type for Publisher. */
export type PublisherConnection = {
  __typename?: 'PublisherConnection';
  /** A list of edges. */
  edges?: Maybe<Array<Maybe<PublisherEdge>>>;
  /** A list of nodes. */
  nodes?: Maybe<Array<Maybe<Publisher>>>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
};

/** An edge in a connection. */
export type PublisherEdge = {
  __typename?: 'PublisherEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['String'];
  /** The item at the end of the edge. */
  node?: Maybe<Publisher>;
};

export type PublisherInput = {
  name?: Maybe<Scalars['String']>;
};

export type Query = {
  __typename?: 'Query';
  book: Book;
  books: BookConnection;
  creator: Creator;
  creators: Array<Creator>;
  publisher: Publisher;
  publishers: PublisherConnection;
  series: Series;
  seriesList: SeriesConnection;
  users: UserConnection;
};


export type QueryBookArgs = {
  id?: Maybe<Scalars['ID']>;
};


export type QueryBooksArgs = {
  sortBy?: Maybe<SortAttributes>;
  limit?: Maybe<Scalars['Int']>;
  after?: Maybe<Scalars['String']>;
  before?: Maybe<Scalars['String']>;
  first?: Maybe<Scalars['Int']>;
  last?: Maybe<Scalars['Int']>;
};


export type QueryCreatorArgs = {
  id?: Maybe<Scalars['ID']>;
};


export type QueryPublisherArgs = {
  id?: Maybe<Scalars['ID']>;
};


export type QueryPublishersArgs = {
  sortBy?: Maybe<SortAttributes>;
  limit?: Maybe<Scalars['Int']>;
  after?: Maybe<Scalars['String']>;
  before?: Maybe<Scalars['String']>;
  first?: Maybe<Scalars['Int']>;
  last?: Maybe<Scalars['Int']>;
};


export type QuerySeriesArgs = {
  id?: Maybe<Scalars['ID']>;
};


export type QuerySeriesListArgs = {
  sortBy?: Maybe<SortAttributes>;
  limit?: Maybe<Scalars['Int']>;
  after?: Maybe<Scalars['String']>;
  before?: Maybe<Scalars['String']>;
  first?: Maybe<Scalars['Int']>;
  last?: Maybe<Scalars['Int']>;
};


export type QueryUsersArgs = {
  sortBy?: Maybe<SortAttributes>;
  limit?: Maybe<Scalars['Int']>;
  after?: Maybe<Scalars['String']>;
  before?: Maybe<Scalars['String']>;
  first?: Maybe<Scalars['Int']>;
  last?: Maybe<Scalars['Int']>;
};

export type RegistrationInput = {
  email: Scalars['String'];
  password: Scalars['String'];
  name: Scalars['String'];
};

/** A collection of related books */
export type Series = {
  __typename?: 'Series';
  bookCount: Scalars['Int'];
  /** A list of books released in this series */
  books?: Maybe<Array<Book>>;
  createdAt: Scalars['DateTime'];
  id: Scalars['ID'];
  name: Scalars['String'];
  publisher?: Maybe<Publisher>;
  publisherName?: Maybe<Scalars['String']>;
  updatedAt: Scalars['DateTime'];
};


/** A collection of related books */
export type SeriesBooksArgs = {
  limit?: Maybe<Scalars['Int']>;
};

/** The connection type for Series. */
export type SeriesConnection = {
  __typename?: 'SeriesConnection';
  /** A list of edges. */
  edges?: Maybe<Array<Maybe<SeriesEdge>>>;
  /** A list of nodes. */
  nodes?: Maybe<Array<Maybe<Series>>>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
};

/** An edge in a connection. */
export type SeriesEdge = {
  __typename?: 'SeriesEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['String'];
  /** The item at the end of the edge. */
  node?: Maybe<Series>;
};

export type SeriesInput = {
  name?: Maybe<Scalars['String']>;
};

/** Attributes for defining the sorting of the query results */
export type SortAttributes = {
  /** name of the field */
  field: Scalars['String'];
  /** direction of the sort */
  direction: SortDirectionEnum;
};

export enum SortDirectionEnum {
  /** Ascending */
  Asc = 'ASC',
  /** Descending */
  Desc = 'DESC'
}

/** Autogenerated return type of UpdateBook */
export type UpdateBookPayload = {
  __typename?: 'UpdateBookPayload';
  book?: Maybe<Book>;
  errors: Array<UserError>;
};

/** Autogenerated return type of UpdatePublisher */
export type UpdatePublisherPayload = {
  __typename?: 'UpdatePublisherPayload';
  errors: Array<UserError>;
  publisher?: Maybe<Publisher>;
};

/** Autogenerated return type of UpdateSeries */
export type UpdateSeriesPayload = {
  __typename?: 'UpdateSeriesPayload';
  errors: Array<UserError>;
  series?: Maybe<Series>;
};

/** A website user */
export type User = {
  __typename?: 'User';
  avatar: Scalars['String'];
  createdAt: Scalars['DateTime'];
  email: Scalars['String'];
  id: Scalars['ID'];
  name: Scalars['String'];
  roles: Array<Scalars['String']>;
  updatedAt: Scalars['DateTime'];
};

/** The connection type for User. */
export type UserConnection = {
  __typename?: 'UserConnection';
  /** A list of edges. */
  edges?: Maybe<Array<Maybe<UserEdge>>>;
  /** A list of nodes. */
  nodes?: Maybe<Array<Maybe<User>>>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
};

/** An edge in a connection. */
export type UserEdge = {
  __typename?: 'UserEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['String'];
  /** The item at the end of the edge. */
  node?: Maybe<User>;
};

/** A user-readable error */
export type UserError = {
  __typename?: 'UserError';
  /** A description of the error */
  message: Scalars['String'];
  /** Which input value this error came from */
  path?: Maybe<Array<Scalars['String']>>;
};

export type BookQueryVariables = Exact<{
  id: Scalars['ID'];
}>;


export type BookQuery = { __typename?: 'Query', book: { __typename?: 'Book', id: string, ageRating?: Maybe<string>, alternateTitle?: Maybe<string>, createdAt: any, displayName: string, format?: Maybe<string>, issue?: Maybe<string>, pageCount?: Maybe<string>, price?: Maybe<string>, publicationDate?: Maybe<string>, summary?: Maybe<string>, updatedAt: any, credits?: Maybe<Array<{ __typename?: 'Credit', role: string, creator: { __typename?: 'Creator', id: string, firstName?: Maybe<string>, lastName?: Maybe<string> } }>>, publisher?: Maybe<{ __typename?: 'Publisher', id: string, name: string }>, series?: Maybe<{ __typename?: 'Series', id: string, name: string }> } };

export type BooksQueryVariables = Exact<{
  limit?: Maybe<Scalars['Int']>;
}>;


export type BooksQuery = { __typename?: 'Query', books: { __typename?: 'BookConnection', nodes?: Maybe<Array<Maybe<{ __typename?: 'Book', id: string, publisherName?: Maybe<string>, seriesName?: Maybe<string>, issue?: Maybe<string>, format?: Maybe<string>, publicationDate?: Maybe<string>, price?: Maybe<string>, pageCount?: Maybe<string> }>>> } };

export type CreatePublisherMutationVariables = Exact<{
  name: Scalars['String'];
}>;


export type CreatePublisherMutation = { __typename?: 'Mutation', createPublisher?: Maybe<{ __typename?: 'CreatePublisherPayload', publisher?: Maybe<{ __typename?: 'Publisher', id: string, name: string }>, errors: Array<{ __typename?: 'UserError', path?: Maybe<Array<string>>, message: string }> }> };

export type CreatorQueryVariables = Exact<{
  id: Scalars['ID'];
}>;


export type CreatorQuery = { __typename?: 'Query', creator: { __typename?: 'Creator', id: string, firstName?: Maybe<string>, lastName?: Maybe<string>, createdAt: any, updatedAt: any, credits: Array<{ __typename?: 'Credit', id: string, role: string, book: { __typename?: 'Book', id: string, displayName: string } }> } };

export type LoginMutationVariables = Exact<{
  email: Scalars['String'];
  password: Scalars['String'];
}>;


export type LoginMutation = { __typename?: 'Mutation', login?: Maybe<{ __typename?: 'AuthenticationResult', accessToken: string, refreshToken: string, me?: Maybe<{ __typename?: 'User', id: string, avatar: string, name: string, email: string, roles: Array<string> }> }> };

export type LogOutMutationVariables = Exact<{
  everywhere?: Maybe<Scalars['Boolean']>;
}>;


export type LogOutMutation = { __typename?: 'Mutation', logout?: Maybe<{ __typename?: 'Message', message: string }> };

export type PublisherQueryVariables = Exact<{
  id: Scalars['ID'];
}>;


export type PublisherQuery = { __typename?: 'Query', publisher: { __typename?: 'Publisher', id: string, name: string, createdAt: any, updatedAt: any, series: Array<{ __typename?: 'Series', id: string, name: string }> } };

export type PublishersQueryVariables = Exact<{ [key: string]: never; }>;


export type PublishersQuery = { __typename?: 'Query', publishers: { __typename?: 'PublisherConnection', nodes?: Maybe<Array<Maybe<{ __typename?: 'Publisher', id: string, name: string, seriesCount: number, series: Array<{ __typename?: 'Series', name: string }> }>>> } };

export type RankedBookListQueryVariables = Exact<{
  limit?: Maybe<Scalars['Int']>;
  field: Scalars['String'];
  direction: SortDirectionEnum;
}>;


export type RankedBookListQuery = { __typename?: 'Query', books: { __typename?: 'BookConnection', nodes?: Maybe<Array<Maybe<{ __typename?: 'Book', id: string, displayName: string, publicationDate?: Maybe<string>, publisherName?: Maybe<string> }>>> } };

export type RankedPublisherListQueryVariables = Exact<{
  limit?: Maybe<Scalars['Int']>;
  field: Scalars['String'];
  direction: SortDirectionEnum;
}>;


export type RankedPublisherListQuery = { __typename?: 'Query', publishers: { __typename?: 'PublisherConnection', nodes?: Maybe<Array<Maybe<{ __typename?: 'Publisher', id: string, name: string, seriesCount: number }>>> } };

export type RankedSeriesListQueryVariables = Exact<{
  limit?: Maybe<Scalars['Int']>;
  field: Scalars['String'];
  direction: SortDirectionEnum;
}>;


export type RankedSeriesListQuery = { __typename?: 'Query', seriesList: { __typename?: 'SeriesConnection', nodes?: Maybe<Array<Maybe<{ __typename?: 'Series', id: string, name: string, publisherName?: Maybe<string>, bookCount: number }>>> } };

export type RegisterMutationVariables = Exact<{
  name: Scalars['String'];
  email: Scalars['String'];
  password: Scalars['String'];
}>;


export type RegisterMutation = { __typename?: 'Mutation', register?: Maybe<{ __typename?: 'AuthenticationResult', accessToken: string, refreshToken: string, me?: Maybe<{ __typename?: 'User', id: string, avatar: string, email: string, name: string, roles: Array<string> }> }> };

export type SeriesQueryVariables = Exact<{
  id: Scalars['ID'];
}>;


export type SeriesQuery = { __typename?: 'Query', series: { __typename?: 'Series', name: string, createdAt: any, updatedAt: any, books?: Maybe<Array<{ __typename?: 'Book', id: string, displayName: string }>> } };

export type UpdatePublisherMutationVariables = Exact<{
  id: Scalars['ID'];
  name: Scalars['String'];
}>;


export type UpdatePublisherMutation = { __typename?: 'Mutation', updatePublisher?: Maybe<{ __typename?: 'UpdatePublisherPayload', publisher?: Maybe<{ __typename?: 'Publisher', id: string, name: string, updatedAt: any }>, errors: Array<{ __typename?: 'UserError', path?: Maybe<Array<string>>, message: string }> }> };

export type UpdateSeriesMutationVariables = Exact<{
  id: Scalars['ID'];
  name: Scalars['String'];
}>;


export type UpdateSeriesMutation = { __typename?: 'Mutation', updateSeries?: Maybe<{ __typename?: 'UpdateSeriesPayload', series?: Maybe<{ __typename?: 'Series', id: string, name: string, updatedAt: any }>, errors: Array<{ __typename?: 'UserError', path?: Maybe<Array<string>>, message: string }> }> };


export const BookDocument = gql`
    query Book($id: ID!) {
  book(id: $id) {
    id
    ageRating
    alternateTitle
    createdAt
    credits {
      creator {
        id
        firstName
        lastName
      }
      role
    }
    displayName
    format
    issue
    pageCount
    price
    publicationDate
    publisher {
      id
      name
    }
    series {
      id
      name
    }
    summary
    updatedAt
  }
}
    `;

/**
 * __useBookQuery__
 *
 * To run a query within a React component, call `useBookQuery` and pass it any options that fit your needs.
 * When your component renders, `useBookQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useBookQuery({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useBookQuery(baseOptions: Apollo.QueryHookOptions<BookQuery, BookQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<BookQuery, BookQueryVariables>(BookDocument, options);
      }
export function useBookLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<BookQuery, BookQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<BookQuery, BookQueryVariables>(BookDocument, options);
        }
export type BookQueryHookResult = ReturnType<typeof useBookQuery>;
export type BookLazyQueryHookResult = ReturnType<typeof useBookLazyQuery>;
export type BookQueryResult = Apollo.QueryResult<BookQuery, BookQueryVariables>;
export const BooksDocument = gql`
    query Books($limit: Int) {
  books(limit: $limit) {
    nodes {
      id
      publisherName
      seriesName
      issue
      format
      publicationDate
      price
      pageCount
    }
  }
}
    `;

/**
 * __useBooksQuery__
 *
 * To run a query within a React component, call `useBooksQuery` and pass it any options that fit your needs.
 * When your component renders, `useBooksQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useBooksQuery({
 *   variables: {
 *      limit: // value for 'limit'
 *   },
 * });
 */
export function useBooksQuery(baseOptions?: Apollo.QueryHookOptions<BooksQuery, BooksQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<BooksQuery, BooksQueryVariables>(BooksDocument, options);
      }
export function useBooksLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<BooksQuery, BooksQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<BooksQuery, BooksQueryVariables>(BooksDocument, options);
        }
export type BooksQueryHookResult = ReturnType<typeof useBooksQuery>;
export type BooksLazyQueryHookResult = ReturnType<typeof useBooksLazyQuery>;
export type BooksQueryResult = Apollo.QueryResult<BooksQuery, BooksQueryVariables>;
export const CreatePublisherDocument = gql`
    mutation CreatePublisher($name: String!) {
  createPublisher(attributes: {name: $name}) {
    publisher {
      id
      name
    }
    errors {
      path
      message
    }
  }
}
    `;
export type CreatePublisherMutationFn = Apollo.MutationFunction<CreatePublisherMutation, CreatePublisherMutationVariables>;

/**
 * __useCreatePublisherMutation__
 *
 * To run a mutation, you first call `useCreatePublisherMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCreatePublisherMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [createPublisherMutation, { data, loading, error }] = useCreatePublisherMutation({
 *   variables: {
 *      name: // value for 'name'
 *   },
 * });
 */
export function useCreatePublisherMutation(baseOptions?: Apollo.MutationHookOptions<CreatePublisherMutation, CreatePublisherMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<CreatePublisherMutation, CreatePublisherMutationVariables>(CreatePublisherDocument, options);
      }
export type CreatePublisherMutationHookResult = ReturnType<typeof useCreatePublisherMutation>;
export type CreatePublisherMutationResult = Apollo.MutationResult<CreatePublisherMutation>;
export type CreatePublisherMutationOptions = Apollo.BaseMutationOptions<CreatePublisherMutation, CreatePublisherMutationVariables>;
export const CreatorDocument = gql`
    query Creator($id: ID!) {
  creator(id: $id) {
    id
    firstName
    lastName
    createdAt
    updatedAt
    credits {
      id
      role
      book {
        id
        displayName
      }
    }
  }
}
    `;

/**
 * __useCreatorQuery__
 *
 * To run a query within a React component, call `useCreatorQuery` and pass it any options that fit your needs.
 * When your component renders, `useCreatorQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useCreatorQuery({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useCreatorQuery(baseOptions: Apollo.QueryHookOptions<CreatorQuery, CreatorQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<CreatorQuery, CreatorQueryVariables>(CreatorDocument, options);
      }
export function useCreatorLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<CreatorQuery, CreatorQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<CreatorQuery, CreatorQueryVariables>(CreatorDocument, options);
        }
export type CreatorQueryHookResult = ReturnType<typeof useCreatorQuery>;
export type CreatorLazyQueryHookResult = ReturnType<typeof useCreatorLazyQuery>;
export type CreatorQueryResult = Apollo.QueryResult<CreatorQuery, CreatorQueryVariables>;
export const LoginDocument = gql`
    mutation Login($email: String!, $password: String!) {
  login(input: {email: $email, password: $password}) {
    me {
      id
      avatar
      name
      email
      roles
    }
    accessToken
    refreshToken
  }
}
    `;
export type LoginMutationFn = Apollo.MutationFunction<LoginMutation, LoginMutationVariables>;

/**
 * __useLoginMutation__
 *
 * To run a mutation, you first call `useLoginMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useLoginMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [loginMutation, { data, loading, error }] = useLoginMutation({
 *   variables: {
 *      email: // value for 'email'
 *      password: // value for 'password'
 *   },
 * });
 */
export function useLoginMutation(baseOptions?: Apollo.MutationHookOptions<LoginMutation, LoginMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<LoginMutation, LoginMutationVariables>(LoginDocument, options);
      }
export type LoginMutationHookResult = ReturnType<typeof useLoginMutation>;
export type LoginMutationResult = Apollo.MutationResult<LoginMutation>;
export type LoginMutationOptions = Apollo.BaseMutationOptions<LoginMutation, LoginMutationVariables>;
export const LogOutDocument = gql`
    mutation LogOut($everywhere: Boolean) {
  logout(input: {everywhere: $everywhere}) {
    message
  }
}
    `;
export type LogOutMutationFn = Apollo.MutationFunction<LogOutMutation, LogOutMutationVariables>;

/**
 * __useLogOutMutation__
 *
 * To run a mutation, you first call `useLogOutMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useLogOutMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [logOutMutation, { data, loading, error }] = useLogOutMutation({
 *   variables: {
 *      everywhere: // value for 'everywhere'
 *   },
 * });
 */
export function useLogOutMutation(baseOptions?: Apollo.MutationHookOptions<LogOutMutation, LogOutMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<LogOutMutation, LogOutMutationVariables>(LogOutDocument, options);
      }
export type LogOutMutationHookResult = ReturnType<typeof useLogOutMutation>;
export type LogOutMutationResult = Apollo.MutationResult<LogOutMutation>;
export type LogOutMutationOptions = Apollo.BaseMutationOptions<LogOutMutation, LogOutMutationVariables>;
export const PublisherDocument = gql`
    query Publisher($id: ID!) {
  publisher(id: $id) {
    id
    name
    createdAt
    updatedAt
    series {
      id
      name
    }
  }
}
    `;

/**
 * __usePublisherQuery__
 *
 * To run a query within a React component, call `usePublisherQuery` and pass it any options that fit your needs.
 * When your component renders, `usePublisherQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = usePublisherQuery({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function usePublisherQuery(baseOptions: Apollo.QueryHookOptions<PublisherQuery, PublisherQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<PublisherQuery, PublisherQueryVariables>(PublisherDocument, options);
      }
export function usePublisherLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<PublisherQuery, PublisherQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<PublisherQuery, PublisherQueryVariables>(PublisherDocument, options);
        }
export type PublisherQueryHookResult = ReturnType<typeof usePublisherQuery>;
export type PublisherLazyQueryHookResult = ReturnType<typeof usePublisherLazyQuery>;
export type PublisherQueryResult = Apollo.QueryResult<PublisherQuery, PublisherQueryVariables>;
export const PublishersDocument = gql`
    query Publishers {
  publishers {
    nodes {
      id
      name
      series {
        name
      }
      seriesCount
    }
  }
}
    `;

/**
 * __usePublishersQuery__
 *
 * To run a query within a React component, call `usePublishersQuery` and pass it any options that fit your needs.
 * When your component renders, `usePublishersQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = usePublishersQuery({
 *   variables: {
 *   },
 * });
 */
export function usePublishersQuery(baseOptions?: Apollo.QueryHookOptions<PublishersQuery, PublishersQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<PublishersQuery, PublishersQueryVariables>(PublishersDocument, options);
      }
export function usePublishersLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<PublishersQuery, PublishersQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<PublishersQuery, PublishersQueryVariables>(PublishersDocument, options);
        }
export type PublishersQueryHookResult = ReturnType<typeof usePublishersQuery>;
export type PublishersLazyQueryHookResult = ReturnType<typeof usePublishersLazyQuery>;
export type PublishersQueryResult = Apollo.QueryResult<PublishersQuery, PublishersQueryVariables>;
export const RankedBookListDocument = gql`
    query RankedBookList($limit: Int, $field: String!, $direction: SortDirectionEnum!) {
  books(limit: $limit, sortBy: {field: $field, direction: $direction}) {
    nodes {
      id
      displayName
      publicationDate
      publisherName
    }
  }
}
    `;

/**
 * __useRankedBookListQuery__
 *
 * To run a query within a React component, call `useRankedBookListQuery` and pass it any options that fit your needs.
 * When your component renders, `useRankedBookListQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useRankedBookListQuery({
 *   variables: {
 *      limit: // value for 'limit'
 *      field: // value for 'field'
 *      direction: // value for 'direction'
 *   },
 * });
 */
export function useRankedBookListQuery(baseOptions: Apollo.QueryHookOptions<RankedBookListQuery, RankedBookListQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<RankedBookListQuery, RankedBookListQueryVariables>(RankedBookListDocument, options);
      }
export function useRankedBookListLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<RankedBookListQuery, RankedBookListQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<RankedBookListQuery, RankedBookListQueryVariables>(RankedBookListDocument, options);
        }
export type RankedBookListQueryHookResult = ReturnType<typeof useRankedBookListQuery>;
export type RankedBookListLazyQueryHookResult = ReturnType<typeof useRankedBookListLazyQuery>;
export type RankedBookListQueryResult = Apollo.QueryResult<RankedBookListQuery, RankedBookListQueryVariables>;
export const RankedPublisherListDocument = gql`
    query RankedPublisherList($limit: Int, $field: String!, $direction: SortDirectionEnum!) {
  publishers(limit: $limit, sortBy: {field: $field, direction: $direction}) {
    nodes {
      id
      name
      seriesCount
    }
  }
}
    `;

/**
 * __useRankedPublisherListQuery__
 *
 * To run a query within a React component, call `useRankedPublisherListQuery` and pass it any options that fit your needs.
 * When your component renders, `useRankedPublisherListQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useRankedPublisherListQuery({
 *   variables: {
 *      limit: // value for 'limit'
 *      field: // value for 'field'
 *      direction: // value for 'direction'
 *   },
 * });
 */
export function useRankedPublisherListQuery(baseOptions: Apollo.QueryHookOptions<RankedPublisherListQuery, RankedPublisherListQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<RankedPublisherListQuery, RankedPublisherListQueryVariables>(RankedPublisherListDocument, options);
      }
export function useRankedPublisherListLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<RankedPublisherListQuery, RankedPublisherListQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<RankedPublisherListQuery, RankedPublisherListQueryVariables>(RankedPublisherListDocument, options);
        }
export type RankedPublisherListQueryHookResult = ReturnType<typeof useRankedPublisherListQuery>;
export type RankedPublisherListLazyQueryHookResult = ReturnType<typeof useRankedPublisherListLazyQuery>;
export type RankedPublisherListQueryResult = Apollo.QueryResult<RankedPublisherListQuery, RankedPublisherListQueryVariables>;
export const RankedSeriesListDocument = gql`
    query RankedSeriesList($limit: Int, $field: String!, $direction: SortDirectionEnum!) {
  seriesList(limit: $limit, sortBy: {field: $field, direction: $direction}) {
    nodes {
      id
      name
      publisherName
      bookCount
    }
  }
}
    `;

/**
 * __useRankedSeriesListQuery__
 *
 * To run a query within a React component, call `useRankedSeriesListQuery` and pass it any options that fit your needs.
 * When your component renders, `useRankedSeriesListQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useRankedSeriesListQuery({
 *   variables: {
 *      limit: // value for 'limit'
 *      field: // value for 'field'
 *      direction: // value for 'direction'
 *   },
 * });
 */
export function useRankedSeriesListQuery(baseOptions: Apollo.QueryHookOptions<RankedSeriesListQuery, RankedSeriesListQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<RankedSeriesListQuery, RankedSeriesListQueryVariables>(RankedSeriesListDocument, options);
      }
export function useRankedSeriesListLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<RankedSeriesListQuery, RankedSeriesListQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<RankedSeriesListQuery, RankedSeriesListQueryVariables>(RankedSeriesListDocument, options);
        }
export type RankedSeriesListQueryHookResult = ReturnType<typeof useRankedSeriesListQuery>;
export type RankedSeriesListLazyQueryHookResult = ReturnType<typeof useRankedSeriesListLazyQuery>;
export type RankedSeriesListQueryResult = Apollo.QueryResult<RankedSeriesListQuery, RankedSeriesListQueryVariables>;
export const RegisterDocument = gql`
    mutation Register($name: String!, $email: String!, $password: String!) {
  register(input: {name: $name, email: $email, password: $password}) {
    me {
      id
      avatar
      email
      name
      roles
    }
    accessToken
    refreshToken
  }
}
    `;
export type RegisterMutationFn = Apollo.MutationFunction<RegisterMutation, RegisterMutationVariables>;

/**
 * __useRegisterMutation__
 *
 * To run a mutation, you first call `useRegisterMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useRegisterMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [registerMutation, { data, loading, error }] = useRegisterMutation({
 *   variables: {
 *      name: // value for 'name'
 *      email: // value for 'email'
 *      password: // value for 'password'
 *   },
 * });
 */
export function useRegisterMutation(baseOptions?: Apollo.MutationHookOptions<RegisterMutation, RegisterMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<RegisterMutation, RegisterMutationVariables>(RegisterDocument, options);
      }
export type RegisterMutationHookResult = ReturnType<typeof useRegisterMutation>;
export type RegisterMutationResult = Apollo.MutationResult<RegisterMutation>;
export type RegisterMutationOptions = Apollo.BaseMutationOptions<RegisterMutation, RegisterMutationVariables>;
export const SeriesDocument = gql`
    query Series($id: ID!) {
  series(id: $id) {
    name
    createdAt
    updatedAt
    books {
      id
      displayName
    }
  }
}
    `;

/**
 * __useSeriesQuery__
 *
 * To run a query within a React component, call `useSeriesQuery` and pass it any options that fit your needs.
 * When your component renders, `useSeriesQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useSeriesQuery({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useSeriesQuery(baseOptions: Apollo.QueryHookOptions<SeriesQuery, SeriesQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<SeriesQuery, SeriesQueryVariables>(SeriesDocument, options);
      }
export function useSeriesLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<SeriesQuery, SeriesQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<SeriesQuery, SeriesQueryVariables>(SeriesDocument, options);
        }
export type SeriesQueryHookResult = ReturnType<typeof useSeriesQuery>;
export type SeriesLazyQueryHookResult = ReturnType<typeof useSeriesLazyQuery>;
export type SeriesQueryResult = Apollo.QueryResult<SeriesQuery, SeriesQueryVariables>;
export const UpdatePublisherDocument = gql`
    mutation UpdatePublisher($id: ID!, $name: String!) {
  updatePublisher(id: $id, attributes: {name: $name}) {
    publisher {
      id
      name
      updatedAt
    }
    errors {
      path
      message
    }
  }
}
    `;
export type UpdatePublisherMutationFn = Apollo.MutationFunction<UpdatePublisherMutation, UpdatePublisherMutationVariables>;

/**
 * __useUpdatePublisherMutation__
 *
 * To run a mutation, you first call `useUpdatePublisherMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useUpdatePublisherMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [updatePublisherMutation, { data, loading, error }] = useUpdatePublisherMutation({
 *   variables: {
 *      id: // value for 'id'
 *      name: // value for 'name'
 *   },
 * });
 */
export function useUpdatePublisherMutation(baseOptions?: Apollo.MutationHookOptions<UpdatePublisherMutation, UpdatePublisherMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<UpdatePublisherMutation, UpdatePublisherMutationVariables>(UpdatePublisherDocument, options);
      }
export type UpdatePublisherMutationHookResult = ReturnType<typeof useUpdatePublisherMutation>;
export type UpdatePublisherMutationResult = Apollo.MutationResult<UpdatePublisherMutation>;
export type UpdatePublisherMutationOptions = Apollo.BaseMutationOptions<UpdatePublisherMutation, UpdatePublisherMutationVariables>;
export const UpdateSeriesDocument = gql`
    mutation UpdateSeries($id: ID!, $name: String!) {
  updateSeries(id: $id, attributes: {name: $name}) {
    series {
      id
      name
      updatedAt
    }
    errors {
      path
      message
    }
  }
}
    `;
export type UpdateSeriesMutationFn = Apollo.MutationFunction<UpdateSeriesMutation, UpdateSeriesMutationVariables>;

/**
 * __useUpdateSeriesMutation__
 *
 * To run a mutation, you first call `useUpdateSeriesMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useUpdateSeriesMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [updateSeriesMutation, { data, loading, error }] = useUpdateSeriesMutation({
 *   variables: {
 *      id: // value for 'id'
 *      name: // value for 'name'
 *   },
 * });
 */
export function useUpdateSeriesMutation(baseOptions?: Apollo.MutationHookOptions<UpdateSeriesMutation, UpdateSeriesMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<UpdateSeriesMutation, UpdateSeriesMutationVariables>(UpdateSeriesDocument, options);
      }
export type UpdateSeriesMutationHookResult = ReturnType<typeof useUpdateSeriesMutation>;
export type UpdateSeriesMutationResult = Apollo.MutationResult<UpdateSeriesMutation>;
export type UpdateSeriesMutationOptions = Apollo.BaseMutationOptions<UpdateSeriesMutation, UpdateSeriesMutationVariables>;