default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: postgres
  # password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  pool: 5

development:
  <<: *default
  database: longbox_development

test:
  <<: *default
  database: longbox_test