source 'https://rubygems.org'

ruby '2.4.1'

gem 'rails', '5.1.2'
gem 'pg'

gem 'haml-rails'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'sass-rails', '~> 5.0'

gem 'database_cleaner', group: :test

group :development, :test do
  gem 'factory_girl_rails'
  gem 'rspec-rails'
end

group :production do
  gem 'rails_12factor'
end