overwrite: true
schema: 'http://api:3000/graphql'
documents: 'src/**/*.graphql'
generates:
  src/types/index.ts:
    - typescript
  src/:
    preset: near-operation-file
    presetConfig:
      baseTypesPath: types.ts
      extension: .generated.tsx
      folder: ../
    plugins:
      - typescript-operations
      - typescript-react-apollo
hooks:
  afterOneFileWrite:
    - yarn lint:fix
