overwrite: true
schema: 'http://api:3000/graphql'
documents: 'src/**/*.graphql'
generates:
  src/hooks/use-graphql.tsx:
    plugins:
      - named-operations-object
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      preResolveTypes: true
