overwrite: true
schema: 'http://api:3000/graphql'
documents: 'src/**/*.graphql'
generates:
  src/types/index.ts:
    - typescript
    - typescript-operations
    - named-operations-object
  src/:
    preset: near-operation-file
    presetConfig:
      baseTypesPath: types.ts
      extension: .generated.tsx
      folder: ../
    plugins:
      - typescript-operations
      - typescript-react-apollo
hooks:
  afterAllFileWrite:
    - yarn run eslint --fix --config config/eslint.config.js '*/**/*generated.tsx' src/types/index.ts
config:
  withResultType: true
