source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '~> 3.0.0'

gem 'rails', '~> 6.1.3'

gem 'pg', '>= 0.18', '< 2.0'

gem 'bootsnap', '>= 1.1.0', require: false
gem 'graphql', '~> 1.12.12'
gem 'puma', '~> 5.3.2'
gem 'rack-cors', '~> 1.1.1'

group :development do
  gem 'faker', '~> 2.18.0'
  gem 'listen', '>= 3.3'
  gem "rubocop", require: false
  gem "rubocop-performance", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-rspec", require: false
  gem 'ruby-progressbar'
  gem 'simplecov', require: false
  gem 'spring', '~> 2.1'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :development, :test do
  gem 'factory_bot_rails', '~> 6.2.0'
  gem 'rspec-graphql_matchers', '~> 1.3.0'
  gem 'rspec-rails', '~> 5.0.1'
  gem 'shoulda-matchers', '~> 4.0'
end
