source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '~> 3.0.0'

# Rails
gem 'rails', '~> 6.1.3'

# Database
gem 'pg', '>= 0.18', '< 2.0'

# Authentication
gem 'bcrypt', '~> 3.1.7'
gem 'jwt'
gem 'rack-cors'
# gem 'simple_token_authentication'

gem 'bootsnap', '>= 1.1.0', require: false
gem 'graphql'
gem 'puma', '~> 5.3.2'
gem 'rack-cors'

group :development do
  gem 'faker'
  gem 'listen', '>= 3.3'
  gem "rubocop", require: false
  gem "rubocop-performance", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-rspec", require: false
  gem 'ruby-progressbar'
  gem 'simplecov', require: false
  gem 'spring', '~> 2.1'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :development, :test do
  gem 'factory_bot_rails'
  gem 'rspec-graphql_matchers'
  gem 'rspec-rails', '~> 5.0.1'
  gem 'shoulda-matchers', '~> 4.0'
end
