source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '~> 2.6'

gem 'rails', '~> 6.0.3', '>= 6.0.3.3'

gem 'graphql'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

group :development do
  gem 'faker'
  gem 'listen', '>= 3.0.5', '< 3.3'
  gem 'spring', '~> 2.1'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :development, :test do
  gem 'rspec-graphql_matchers'
  gem 'rspec-rails'
end
