name: "Publish: Proxy package [dev]"

on:
  push:
    branches: [develop]
    paths:
      - "proxy/**"
  workflow_dispatch:
    branches: [develop]
    paths:
      - "proxy/**"

defaults:
  run:
    working-directory: ./proxy

jobs:
  build-container:
    name: Build Docker container image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Publish to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository}}/web
          dockerfile: ./proxy/Dockerfile
          tags: dev, ${{ github.run_number }}
