name: "Publish: Proxy package [dev]"

on:
  push:
    branches: [develop]
    paths:
      - "proxy/**"
  workflow_dispatch:
    branches: [develop]
    paths:
      - "proxy/**"

jobs:
  build-container:
    name: Build Docker container image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and Publish
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./proxy
          registry: docker.pkg.github.com
          tags: ${{ github.repository}}/proxy, dev, ${{ github.run_number }}
