name: "Publish: API package [dev]"

env:
  app_name: api
  version: 1

on:
  push:
    branches: [develop]
    paths:
      - "${{ env.app_name }}/**"
  workflow_dispatch:
    branches: [develop]
    paths:
      - "${{ env.app_name }}/**"

jobs:
  build-container:
    name: Build Docker container image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and Publish
        uses: docker/build-push-action@v2
        with:
          push: true
          context: "./${{ env.app_name }}"
          tags: |
            ghcr.io/${{ github.repository}}/${{ env.app_name }}:${{ env.version }}.${{ github.run_number }}-dev
