name: "Publish: Proxy package [dev]"

on:
  push:
    branches: [main]
    paths:
      - "proxy/**"
  workflow_dispatch:
    branches: [main]
    paths:
      - "proxy/**"

jobs:
  build-container:
    name: Build Docker container image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to GitHub Packages
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and Publish
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          context: "./proxy"
          tags: |
            ghcr.io/${{ github.repository}}/proxy:latest-dev
            ghcr.io/${{ github.repository}}/proxy:1.${{ github.run_number }}-dev
