name: "API: Ruby"

on:
  push:
    branches: [master, develop]
    paths:
      - "api/**"
  pull_request:
    branches: [master, develop]
    paths:
      - "api/**"

defaults:
  run:
    working-directory: api

env:
  RUBY_VERSION: 2.7.2
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  POSTGRES_DB: postgres

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: "Rubocop: install"
        run: |
          gem install -N rubocop rubocop-rails rubocop-rspec rubocop-performance

      - name: "Rubocop: run"
        run: |
          rubocop --format github

  brakeman:
    name: Brakeman
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: "Brakeman: install"
        run: |
          gem install brakeman

      - name: "Brakeman: run"
        run: |
          brakeman

  # test:
  #   runs-on: ubuntu-latest

  #   services:
  #     postgres:
  #       image: postgres:11
  #       ports: ["5432:5432"]
  #       env:
  #         POSTGRES_PASSWORD: postgres

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Setup Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: ${{ env.RUBY_VERSION }}

  #     - uses: Borales/actions-yarn@v2.3.0
  #       with:
  #         cmd: install

  #     - name: Install Dependencies
  #       run: |
  #         sudo apt install -yqq libpq-dev
  #         gem install bundler

  #     - name: Install Gems
  #       run: |
  #         bundle install

  #     - name: Prepare Database
  #       run: |
  #         bundle exec rails db:prepare

  #     - name: Run Tests
  #       env:
  #         DATABASE_URL: postgres://postgres:postgres@localhost:5432/databasename
  #         RAILS_MASTER_KEY: ${{secrets.RAILS_MASTER_KEY}}
  #       run: |
  #         bundle exec rails test
