name: "Test: API ruby code"

on:
  pull_request:
    branches: [main, develop]
    paths:
      - "api/**"
  push:
    branches: [main, develop]
    paths:
      - "api/**"
  workflow_dispatch:
    branches: [main, develop]
    paths:
      - "api/**"

defaults:
  run:
    working-directory: api

env:
  RUBY_VERSION: 3.0.0
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  POSTGRES_DB: postgres

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: "Rubocop: install"
        run: |
          gem install -N rubocop rubocop-rails rubocop-rspec rubocop-performance

      - name: "Rubocop: run"
        run: |
          rubocop --format github

  brakeman:
    name: Brakeman
    runs-on: ubuntu-latest
    steps:
      - name: "Setup: Checkout"
        uses: actions/checkout@v2.3.4

      - name: "Setup: Ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: "Brakeman: install"
        run: |
          gem install brakeman

      - name: "Brakeman: run"
        continue-on-error: true
        run: |
          brakeman -f sarif -o output.sarif.json .

      - name: "Cleanup: Upload SARIF"
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: output.sarif.json

  rspec-test:
    name: RSpec
    needs: [rubocop, brakeman]
    runs-on: ubuntu-18.04
    steps:
      - name: "Setup: Checkout"
        uses: actions/checkout@v2.3.4

      - name: "Setup: Ruby"
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: "Setup: Install postgres client"
        run: sudo apt-get install libpq-dev

      - name: "Setup: Install gem dependencies"
        run: |
          gem install bundler
          bundler install

      - name: "Setup: Create database"
        run: |
          bundler exec rails db:create RAILS_ENV=test
          bundler exec rails db:migrate RAILS_ENV=test

      - name: "Rspec: Run tests"
        run: bundler exec rake
