name: "Test: Web typescript code"

on:
  pull_request:
    branches: [main, develop]
    paths:
      - "web/**"
  push:
    branches: [main, develop]
    paths:
      - "web/**"
  workflow_dispatch:
    branches: [main, develop]
    paths:
      - "web/**"

defaults:
  run:
    working-directory: web

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0

      - uses: actions/setup-node@v3
        with:
          node-version: "12"

      - run: yarn install

      - name: "ESLint: run"
        run: yarn run lint
